# YouTube link parsing
youtube:
  enabled: false
  api-key: "api-key-here"
wolframalpha:
  enabled: false
  api-key: "api-key-here"
pastebin:
  enabled: false
  api-key: "api-key-here"
# Channels here will automatically be joined
channels:
- "#royalbot"
# Must be authed by NickServ
admins:
- WizardCM
# Cannot have power removed
superadmin: jkcclemens
